# Generated by Django 4.2.30 on 2026-06-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport', models.CharField(choices=[('FB', 'Fútbol'), ('BK', 'Básquet')], default='FB', max_length=2, verbose_name='Deporte')),
                ('home_team', models.CharField(max_length=100, verbose_name='Equipo Local')),
                ('away_team', models.CharField(max_length=100, verbose_name='Equipo Visitante')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='Resultado Local')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='Resultado Visitante')),
                ('date', models.DateField(verbose_name='Fecha del Partido')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
            ],
            options={
                'verbose_name': 'Partido',
                'verbose_name_plural': 'Partidos',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
