# Generated by Django 4.2.30 on 2026-06-09 22:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del Grupo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del Equipo')),
                ('flag', models.CharField(default='🏳️', max_length=10, verbose_name='Bandera (Emoji)')),
                ('games_played', models.PositiveIntegerField(default=0, verbose_name='PJ')),
                ('wins', models.PositiveIntegerField(default=0, verbose_name='G')),
                ('draws', models.PositiveIntegerField(default=0, verbose_name='E')),
                ('losses', models.PositiveIntegerField(default=0, verbose_name='P')),
                ('goals_for', models.PositiveIntegerField(default=0, verbose_name='GF')),
                ('goals_against', models.PositiveIntegerField(default=0, verbose_name='GC')),
                ('points', models.PositiveIntegerField(default=0, verbose_name='Pts')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tracker.group', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Equipo de Grupo',
                'verbose_name_plural': 'Equipos de Grupo',
                'unique_together': {('group', 'name')},
            },
        ),
        migrations.CreateModel(
            name='GroupMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='Goles Local')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='Goles Visitante')),
                ('played', models.BooleanField(default=True, verbose_name='Jugado')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tracker.groupteam', verbose_name='Equipo Visitante')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tracker.group', verbose_name='Grupo')),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tracker.groupteam', verbose_name='Equipo Local')),
            ],
            options={
                'verbose_name': 'Partido de Grupo',
                'verbose_name_plural': 'Partidos de Grupo',
                'ordering': ['created_at'],
            },
        ),
    ]
