# Generated by Django 4.2.30 on 2026-06-10 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_group_groupteam_groupmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmatch',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Partido'),
        ),
        migrations.AlterField(
            model_name='groupmatch',
            name='played',
            field=models.BooleanField(default=False, verbose_name='Jugado'),
        ),
    ]
