# Generated by Django 4.2.30 on 2026-06-10 01:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_groupmatch_date_alter_groupmatch_played'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnockoutMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(choices=[('R32', 'Dieciseisavos de Final'), ('R16', 'Octavos de Final'), ('QF', 'Cuartos de Final'), ('SF', 'Semifinales'), ('F', 'Final')], max_length=5, verbose_name='Ronda')),
                ('match_number', models.PositiveIntegerField(verbose_name='Número de Partido')),
                ('home_score', models.PositiveIntegerField(default=0, verbose_name='Goles Local')),
                ('away_score', models.PositiveIntegerField(default=0, verbose_name='Goles Visitante')),
                ('home_penalties', models.PositiveIntegerField(blank=True, null=True, verbose_name='Penaltis Local')),
                ('away_penalties', models.PositiveIntegerField(blank=True, null=True, verbose_name='Penaltis Visitante')),
                ('played', models.BooleanField(default=False, verbose_name='Jugado')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha del Partido')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('away_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='away_knockout_matches', to='tracker.groupteam', verbose_name='Equipo Visitante')),
                ('home_team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_knockout_matches', to='tracker.groupteam', verbose_name='Equipo Local')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_knockout_matches', to='tracker.groupteam', verbose_name='Ganador')),
            ],
            options={
                'verbose_name': 'Partido de Eliminación Directa',
                'verbose_name_plural': 'Partidos de Eliminación Directa',
                'ordering': ['round', 'match_number'],
                'unique_together': {('round', 'match_number')},
            },
        ),
    ]
